dtb-$(CONFIG_ARCH_R8A7795) += r8a7795-salvator-x.dtb r8a7795-h3ulcb.dtb \
			      r8a7795-salvator-x-view.dtb r8a7795-h3ulcb-had.dtb \
			      r8a7795-h3ulcb-view.dtb r8a7795-salvator-x-dom0.dtb
dtb-$(CONFIG_ARCH_R8A7796) += r8a7796-salvator-x.dtb r8a7796-m3ulcb.dtb \
			      r8a7796-salvator-x-view.dtb r8a7796-m3ulcb-view.dtb

always		:= $(dtb-y)
clean-files	:= *.dtb
